Added CDK code for XWiki demo installation with unit tests.
xwiki-contrib/aws pull request #6
Opened 2021-06-20 18:52 UTC by sanchita141011

Added CDK code for installing XWiki demo using user-script on EC2 instance of type T2.medium inside public subnet of default VPC of the user's account. Added unit tests using jest test framework.

2021-06-21 07:04 UTC, 9inpachi requested changes
Hi @sanchita141011,

The code styling seems a bit inconsistent, could you maybe set up [prettier](https://github.com/prettier/prettier) and ideally eslint as well? It would make it easier to maintain code checking and styling for the future. ;)

2021-06-21 14:21 UTC, sanchita141011 commented
> Hi @sanchita141011,
> 
> The code styling seems a bit inconsistent, could you maybe set up [prettier](https://github.com/prettier/prettier) and ideally [eslint](https://github.com/eslint/eslint) as well? It would make it easier to maintain code checking and styling for the future. ;)

Thankyou for suggestion. :)

2021-06-21 16:21 UTC, 9inpachi approved these changes
Looks good to me (TypeScript-wise — I don't know much about CDK). ;)
Thanks for the changes.

2021-06-24 18:48 UTC, sachin10101998 reviewed
Add better tests. Remove import * statements. Add entry point file to this cdk app. Currently, there's only single stack with no entry point for this application. This code won't work.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +import * as cdk from '@aws-cdk/core'
Remove all * imports. Import only the modules you want in the file.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +import * as ec2 from '@aws-cdk/aws-ec2'
Remove all * imports. Import only the modules you want in the file.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +import * as iam from '@aws-cdk/aws-iam'
Remove all * imports. Import only the modules you want in the file.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +  constructor (scope: cdk.Construct, id: string, props?: cdk.StackProps) {
Scope here should be cdp.App and not cdk.Construct

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +    const defaultVpc = ec2.Vpc.fromLookup(this, 'VPC', { isDefault: true })
Don't hard code VPC. In case default vpc is not present , then the code will fail. Take it from the consumer. Give him the flexibility to choose default vpc or create a new one or pass any other vpc. Manage it in entry point of the cdk application.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/test/xwiki-demo-cdk.test.ts
> +import * as cdk from '@aws-cdk/core'
Dont use import * statements.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/test/xwiki-demo-cdk.test.ts
> +  expectCDK(stack).to(
Add snapshot tests for CDK.

2021-06-24 18:48 UTC, sachin10101998 commented on xwiki-demo-cdk/test/xwiki-demo-cdk.test.ts
> +
dd more granular tests. Just testing the presence of ec2 instance is not gonna make it. Check for other resources you created via CDK too.

2021-06-24 22:09 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +import * as cdk from '@aws-cdk/core'
Done :)

2021-06-24 22:09 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +import * as ec2 from '@aws-cdk/aws-ec2'
Done :)

2021-06-24 22:09 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +  constructor (scope: cdk.Construct, id: string, props?: cdk.StackProps) {
corrected :)

2021-06-24 22:10 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +    const defaultVpc = ec2.Vpc.fromLookup(this, 'VPC', { isDefault: true })
Changed the VPC from default to new VPC.

2021-06-24 22:10 UTC, sanchita141011 commented on xwiki-demo-cdk/test/xwiki-demo-cdk.test.ts
> +  expectCDK(stack).to(
Added snapshot test

2021-06-25 03:44 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +import * as iam from '@aws-cdk/aws-iam'
Done :)

2021-06-25 03:44 UTC, sanchita141011 commented on xwiki-demo-cdk/test/xwiki-demo-cdk.test.ts
> +import * as cdk from '@aws-cdk/core'
Done

2021-06-25 03:45 UTC, sanchita141011 commented on xwiki-demo-cdk/test/xwiki-demo-cdk.test.ts
> +
added unit test to check EC2 instance, VPC, IAM Role, Security Group and to check if EC2 instance is launched inside a subnet with public IPv4. Please check and suggest changes If required

2021-06-26 15:46 UTC, sachin10101998 reviewed
Add more granular tests is possible.

2021-06-26 15:46 UTC, sachin10101998 commented on xwiki-demo-cdk/Bin/xwiki-demo-cdk.ts
> +    region: 'eu-central-1'
Dont hard code the region. Get it from some configuration file as discussed

2021-06-26 15:46 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/Ec2-model.ts
> +export interface ec2props extends StackProps{
Add JavaDoc for all classes. Explain parameters in comments. What's the use of each.

2021-06-26 15:46 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +    // const commands = ['sudo yum -q -y install java-1.8.0-openjdk && sudo yum -q -y install unzip && mkdir xwikihome && wget -q -O xwiki_packer.zip https://nexus.xwiki.org/nexus/content/groups/publ
Remove these lines if they are not needed.

2021-06-26 15:46 UTC, sachin10101998 commented on xwiki-demo-cdk/lib/stacks/user_script.sh
> +wget -q -O xwiki_packer.zip https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-flavor-jetty-hsqldb/13.1/xwiki-platform-distribution-flavor-jetty-hsqldb
Remove this file.

2021-06-26 23:21 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/Ec2-model.ts
> +export interface ec2props extends StackProps{
Done. Please suggest the changes if required

2021-06-26 23:21 UTC, sanchita141011 commented on xwiki-demo-cdk/lib/stacks/ec2-xwiki-demo.ts
> +    // const commands = ['sudo yum -q -y install java-1.8.0-openjdk && sudo yum -q -y install unzip && mkdir xwikihome && wget -q -O xwiki_packer.zip https://nexus.xwiki.org/nexus/content/groups/publ
Removed

2021-06-28 14:03 UTC, merged

2021-06-28 14:04 UTC, sachin10101998 commented
Good work on the PR. Hope to get the Production PR merged too soon after it's completed.